name: auto_screenshot
description: Grabs screenshots from your Flutter app on multiple platforms (iOS or Android)
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  checked_yaml: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_annotation: ^4.6.0
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  json_serializable: ^6.3.2
  build_runner: ^2.2.1

executables:
  auto_screenshot
  validate

funding:
  - https://paypal.me/isaaclyman